### ISSUE TITLE
java.lang.AssertionError: 115

### ISSUE THREAD

**Issue by ksdev-pl** [Vektah/CodeGlance#112]
Hello

A new kind of exception for me (I don't know how to repeat it):

`PhpStorm 2016.1`

```
115
java.lang.AssertionError: 115
    at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
    at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
    at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
    at net.vektah.codeglance.render.Minimap.update(Minimap.kt:250)
    at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
    at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
    at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by JD-Robbs** [comment]
Same here:

    63
    java.lang.AssertionError: 63
	at     com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:250)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bendem** [comment]
Exception is thrown from [here](https://github.com/JetBrains/intellij-community/blob/283dc33e0dc2fd72792133b47409a57481c59592/platform/core-impl/src/com/intellij/openapi/editor/impl/IntervalTreeImpl.java#L221)

**Comment by arkuuu** [comment]
Had this today, too:
```
80
java.lang.AssertionError: 80
	at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:267)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)
```

It happened after I switched between two change lists and PHPStorm asked me to remove the old empty change list. All editor windows where closed during this and the blank editor window was displayed.
This was the second time it crashed for me during the exact same operation, so it seems reproducible.

**Comment by huebs** [comment]
Same here:

```java
70
java.lang.AssertionError: 70
	at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getEndOffset(RangeMarkerImpl.java:94)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
	at net.vektah.codeglance.render.Minimap.updateDimensions(Minimap.kt:68)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:219)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)
```

I had just folded a large block of code.

**Comment by enidvangils** [comment]
Same here:
```
112
java.lang.AssertionError: 112
	at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:250)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)
```
No idea what I was doing!

**Comment by Potherca** [comment]
Same here (PHPStorm 2016.2)

```
87
java.lang.AssertionError: 87
	at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getEndOffset(RangeMarkerImpl.java:94)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:250)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)
```
