### ISSUE TITLE
AssertionError: 221

### ISSUE THREAD

**Issue by voidburn** [Vektah/CodeGlance#121]
```
java.lang.AssertionError: 221
    at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
    at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
    at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
    at net.vektah.codeglance.render.Minimap.update(Minimap.kt:250)
    at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
    at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
    at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by jimmywan** [comment]
Duplicate of #112
