### ISSUE TITLE
CodeGlance threw an uncaught AssertionError

### ISSUE THREAD

**Issue by YiiGuxing** [Vektah/CodeGlance#124]
```
java.lang.AssertionError: 64
    at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
    at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
    at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
    at net.vektah.codeglance.render.Minimap.update(Minimap.kt:250)
    at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
    at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
    at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by jimmywan** [comment]
I'm guessing this isn't terribly helpful, but I got the same error with a different number:
```
72
java.lang.AssertionError: 72
	at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:250)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)
```
