### ISSUE TITLE
AssertionError: 245

### ISSUE THREAD

**Issue by approxit** [Vektah/CodeGlance#142]
CodeGlance 1.4.4, PyCharm 2016.3
```
java.lang.AssertionError: 245
	at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
	at net.vektah.codeglance.render.Minimap.updateDimensions(Minimap.kt:68)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:219)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)
```
Just random exception.

**Comment by singalen** [comment]
+1. Opened a large standard library file and quickly closed.

```
java.lang.AssertionError: 71
	at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:250)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by approxit** [comment]
I must agree with @singalen. Exception is linked with very long files.
