### ISSUE TITLE
java.lang.AssertionError: 65

### ISSUE THREAD

**Issue by hakil** [Vektah/CodeGlance#148]
65
java.lang.AssertionError: 65
	at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:250)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hill0826** [comment]
Seeing this same thing from time to time. Minor annoyance, but it seems like it might mess up the Code Glance pane from time to time. Exception message is of course not very verbose.
