### ISSUE TITLE
java.lang.AssertionError: 71

### ISSUE THREAD

**Issue by approxit** [Vektah/CodeGlance#152]
```
71
java.lang.AssertionError: 71
	at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:250)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by aronbeal** [comment]
Believe I encountered this as well, although I think it's moved in the codebase since then:

77
java.lang.AssertionError: 77
	at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
	at net.vektah.codeglance.render.Minimap.updateDimensions(Minimap.kt:68)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:219)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)

Just editing a behat feature file at the time, didn't even notice the error until I saw the blinking red exclamation point in the corner of the IDE.  No idea what fallout it had.
