### ISSUE TITLE
CodeGlance broken in latest WebStorm 2017.1

### ISSUE THREAD

**Issue by born2net** [Vektah/CodeGlance#155]
WebStorm 2017.1 EAP
Build #WS-171.3566.29, built on February 22, 2017
WebStorm EAP User
Expiration date: March 24, 2017
JRE: 1.8.0_112-release-724-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

does not load at all :(

regards

Sean

**Comment by Serge-Goujon** [comment]
Same here. But for me it starts normally but then crashing on debug or code inspection operations.

**Comment by Serge-Goujon** [comment]
FYI.
Error message: no such child: 1
Details: No such child: 1
java.lang.ArrayIndexOutOfBoundsException: No such child: 1
	at java.awt.Container.getComponent(Container.java:334)
	at net.vektah.codeglance.EditorPanelInjector.inject(EditorPanelInjector.kt:50)
	at net.vektah.codeglance.EditorPanelInjector.fileOpened(EditorPanelInjector.kt:25)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:380)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
	at com.sun.proxy.$Proxy91.fileOpened(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.c(FileEditorManagerImpl.java:938)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$5$1.run(FileEditorManagerImpl.java:1031)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.b(FocusManagerImpl.java:655)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.c(FocusManagerImpl.java:639)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.k(FocusManagerImpl.java:609)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:61)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:107)
	at com.intellij.openapi.util.EdtRunnable.lambda$run$0(EdtRunnable.java:27)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2621)
	at com.intellij.openapi.util.EdtRunnable.run(EdtRunnable.java:25)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Serge-Goujon** [comment]
Sorry, haven't noticed it was about WebStorm. In my case it's PhpStorm.

PhpStorm 2017.1 EAP
Build #PS-171.3566.28, built on February 22, 2017
PhpStorm EAP User
Expiration date: March 24, 2017
JRE: 1.8.0_112-release-724-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by Vektah** [comment]
It looks like the new EAPs may have broken the nasty way I inject the panel into the editor.

I will try to find some time over the weekend to work around it.

**Comment by born2net** [comment]
tx for looking into this, love this plugin

**Comment by born2net** [comment]
let us know if you found anything, tx again,
Sean.

**Comment by Serge-Goujon** [comment]
Thanks Vektah, your plugin is awesome. Can't code without it. ))

**Comment by Vektah** [comment]
Please try installing https://github.com/Vektah/CodeGlance/releases/download/1.4.5/CodeGlance-1.4.5.zip

If everything looks good Ill push it up to the intellij plugin repo for all.

**Comment by born2net** [comment]
to which folder do I unzip it?
regards

**Comment by Vektah** [comment]
You don't need to unzip it, just download and go to settings -> plugins -> install local file

I'm not at my computer right now, the labels might not be quite right...

**Comment by born2net** [comment]
great will check asap

**Comment by illusive-man** [comment]
Installed 1.4.6 in PhpStorm - works like a charm! Thank you very much, Vektah.

**Comment by born2net** [comment]
awesome job!!! works great - Thank you very much, Vektah.
