### ISSUE TITLE
Plugin stopped working in 2021.1.3

### ISSUE THREAD

**Issue by dinoluck** [Vektah/CodeGlance#255]
It is still installed and enabled, but the actual minimap is gone. Tried reinstalling, disable/enable, all the works, it is not working.

**Comment by foosel** [comment]
I found that this fork: https://plugins.jetbrains.com/plugin/15562-codeglance2 still works for me.

**Comment by bestv5** [comment]
I rebuild it in 2020.3 https://github.com/ranbest/CodeGlance/releases/tag/v2.0

**Comment by remcokalf** [comment]
Same here.

@ranbest tried to install but installation does not work.

The Codeglance 2 fork mentioned by @foosel works, but has serious scrolling issues in long files, just like the original.

This fork was okay until recently:

https://github.com/mgziminsky/Minimap-for-Jetbrains

But also stopped functioning in recent PHPStorm versions.

Seems there is no good alternative anymore.

**Comment by bestv5** [comment]
> Same here.
> 
> @ranbest tried to install but installation does not work.
> 
> The Codeglance 2 fork mentioned by @foosel works, but has serious scrolling issues in long files, just like the original.
> 
> This fork was okay until recently:
> 
> https://github.com/mgziminsky/Minimap-for-Jetbrains
> 
> But also stopped functioning in recent PHPStorm versions.
> 
> Seems there is no good alternative anymore.

I'm sorry, I had found the serious scrolling issues too.  bug I don't know the Kolin development language。mybe  I can't solve it，But I try my best。

I will  rebuild it   with  2021.1.3

**Comment by bestv5** [comment]
> Same here.
> 
> @ranbest tried to install but installation does not work.
> 
> The Codeglance 2 fork mentioned by @foosel works, but has serious scrolling issues in long files, just like the original.
> 
> This fork was okay until recently:
> 
> https://github.com/mgziminsky/Minimap-for-Jetbrains
> 
> But also stopped functioning in recent PHPStorm versions.
> 
> Seems there is no good alternative anymore.

hello,  please download the plugin file  from  https://github.com/ranbest/CodeGlance/releases/tag/v2.1.0 
and  try it。

**Comment by remcokalf** [comment]
@ranbest Your new version works great (in PHPStorm 2021.1.4). Also no scroll lag issues. This is very nice! Thank you so much!

**Comment by remcokalf** [comment]
@ranbest There is no option to open an issue in your repo. Your version generates an IDE error sometimes, see below. It seems to keep working okay after the IDE error.

```
Worker exited due to exception

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.getAttributesKeys(LexerEditorHighlighter.java:492)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.getAttributes(LexerEditorHighlighter.java:484)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$HighlighterIteratorImpl.getTextAttributes(LexerEditorHighlighter.java:626)
	at com.intellij.openapi.editor.ex.util.LayeredLexerEditorHighlighter$LayeredHighlighterIteratorImpl.getTextAttributes(LayeredLexerEditorHighlighter.java:587)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:117)
	at net.vektah.codeglance.GlancePanel$7.computeInReadAction(GlancePanel.kt:144)
	at com.intellij.openapi.progress.util.ReadTask.performInReadAction(ReadTask.java:49)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:263)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:261)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:211)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

![Schermafbeelding 2021-07-23 om 12 03 21](https://user-images.githubusercontent.com/4609920/126767699-4e6c0561-6f04-4c23-a687-ff305614a880.png)

**Comment by bestv5** [comment]
> @ranbest There is no option to open an issue in your repo. Your version generates an IDE error sometimes, see below. It seems to keep working okay after the IDE error.
> 
> ```
> Worker exited due to exception
> 
> java.util.ConcurrentModificationException
> 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
> 	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.getAttributesKeys(LexerEditorHighlighter.java:492)
> 	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.getAttributes(LexerEditorHighlighter.java:484)
> 	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$HighlighterIteratorImpl.getTextAttributes(LexerEditorHighlighter.java:626)
> 	at com.intellij.openapi.editor.ex.util.LayeredLexerEditorHighlighter$LayeredHighlighterIteratorImpl.getTextAttributes(LayeredLexerEditorHighlighter.java:587)
> 	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:117)
> 	at net.vektah.codeglance.GlancePanel$7.computeInReadAction(GlancePanel.kt:144)
> 	at com.intellij.openapi.progress.util.ReadTask.performInReadAction(ReadTask.java:49)
> 	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
> 	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
> 	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:263)
> 	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
> 	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:261)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:211)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> ```
> 
> ![Schermafbeelding 2021-07-23 om 12 03 21](https://user-images.githubusercontent.com/4609920/126767699-4e6c0561-6f04-4c23-a687-ff305614a880.png)

 i also found this issue， I'll have a look next week。
I've opened the issues  permissions

**Comment by bestv5** [comment]
> @ranbest There is no option to open an issue in your repo. Your version generates an IDE error sometimes, see below. It seems to keep working okay after the IDE error.
> 
> ```
> Worker exited due to exception
> 
> java.util.ConcurrentModificationException
> 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
> 	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.getAttributesKeys(LexerEditorHighlighter.java:492)
> 	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.getAttributes(LexerEditorHighlighter.java:484)
> 	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$HighlighterIteratorImpl.getTextAttributes(LexerEditorHighlighter.java:626)
> 	at com.intellij.openapi.editor.ex.util.LayeredLexerEditorHighlighter$LayeredHighlighterIteratorImpl.getTextAttributes(LayeredLexerEditorHighlighter.java:587)
> 	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:117)
> 	at net.vektah.codeglance.GlancePanel$7.computeInReadAction(GlancePanel.kt:144)
> 	at com.intellij.openapi.progress.util.ReadTask.performInReadAction(ReadTask.java:49)
> 	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
> 	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
> 	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:263)
> 	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
> 	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:261)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:211)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> ```
> 
> ![Schermafbeelding 2021-07-23 om 12 03 21](https://user-images.githubusercontent.com/4609920/126767699-4e6c0561-6f04-4c23-a687-ff305614a880.png)

hello  ，https://github.com/ranbest/CodeGlance/releases/tag/v2.1.1，  please download pre release version，and try it。

**Comment by remcokalf** [comment]
I just tried to install the pre-release version, but I get this error on install:

![Schermafbeelding 2021-08-20 om 14 17 03](https://user-images.githubusercontent.com/4609920/130232046-2c5be336-65f4-4274-8927-8c1cd4ae516f.png)

**Comment by bestv5** [comment]
> I just tried to install the pre-release version, but I get this error on install:
> 
> ![Schermafbeelding 2021-08-20 om 14 17 03](https://user-images.githubusercontent.com/4609920/130232046-2c5be336-65f4-4274-8927-8c1cd4ae516f.png)

hello ，https://github.com/ranbest/CodeGlance/releases/tag/v2.1.1  
 please download pre release version，and try it

if  you has  any problem，please  submit issue in my  repo  https://github.com/ranbest/CodeGlance.  3q

**Comment by remcokalf** [comment]
I got an update option in PHPStorm itself now, and updating worked. Thanks!
