### ISSUE TITLE
Exception thrown with IntelliJ build 141.1192

### ISSUE THREAD

**Issue by MuppetGate** [Vektah/CodeGlance#79]
Not sure what's causing it. I'll try to spot a pattern.

Argument for @NotNull parameter 'listener' of com/intellij/openapi/editor/impl/DocumentImpl.removeDocumentListener must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'listener' of com/intellij/openapi/editor/impl/DocumentImpl.removeDocumentListener must not be null
	at com.intellij.openapi.editor.impl.DocumentImpl.removeDocumentListener(DocumentImpl.java)
	at net.vektah.codeglance.GlancePanel.onClose(GlancePanel.java:323)
	at net.vektah.codeglance.EditorPanelInjector.fileClosed(EditorPanelInjector.java:137)
	at sun.reflect.GeneratedMethodAccessor248.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:322)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:309)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:295)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:288)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
	at com.sun.proxy.$Proxy103.fileClosed(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.EditorWindow$3$1.run(EditorWindow.java:376)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$14$1.run(FileEditorManagerImpl.java:1016)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:672)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:656)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:626)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$11.run(FocusManagerImpl.java:522)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2344)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:500)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:59)
	at com.intellij.ui.tabs.impl.JBTabsImpl.removeDeferred(JBTabsImpl.java:1037)
	at com.intellij.ui.tabs.impl.JBTabsImpl.access$2300(JBTabsImpl.java:64)
	at com.intellij.ui.tabs.impl.JBTabsImpl$15.run(JBTabsImpl.java:924)
	at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:59)
	at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:69)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$7$4$1.run(FocusManagerImpl.java:315)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2344)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$7$4.run(FocusManagerImpl.java:311)
	at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:101)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:108)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:308)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by MuppetGate** [comment]
Right. This error gets thrown when you switch a branch in Git. I'm assuming the problem is caused by the file contents being suddenly replaced while the codeglance window is open.

**Comment by Vektah** [comment]
Fixed in 1.4.3
